In [107]:
import warnings
warnings.filterwarnings('ignore')

In [108]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from datetime import date, timedelta


%matplotlib inline

In [109]:
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly as py
import plotly.graph_objs as go
import plotly.figure_factory as ff
from plotly.subplots import make_subplots


init_notebook_mode(connected=True)

## Explanatory analysis

Current analysis includes:
 - [Confirmed cases globally](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) (country/region, province/state);
 - [Deaths globally](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv) (country/region, province/state).

### Total confirmed cases

In [110]:
df_confirmed = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')
df_confirmed.fillna('None', inplace = True)

In [111]:
df_confirmed.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20,3/21/20,3/22/20,3/23/20,3/24/20
0,None,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,16,21,22,22,22,24,24,40,40,74
1,None,Albania,41.1533,20.1683,0,0,0,0,0,0,...,42,51,55,59,64,70,76,89,104,123
2,None,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,48,54,60,74,87,90,139,201,230,264
3,None,Andorra,42.5063,1.5218,0,0,0,0,0,0,...,1,2,39,39,53,75,88,113,133,164
4,None,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,0,0,0,0,0,1,2,2,3,3

In [112]:
df_confirmed['Last cumulative'] = df_confirmed.iloc[:, -1]

The data is structured in a way, that each consequent date contains **cummulative sum** of confirmed cases.

In [113]:
print('Confirmed cases by', date.today()- timedelta(days=1))

Confirmed cases by 2020-03-24

In [114]:
total_confirmed = df_confirmed[['Country/Region', 'Last cumulative']]
total_confirmed= total_confirmed.groupby('Country/Region')['Last cumulative'].sum().to_frame()
total_confirmed.sort_values('Last cumulative', ascending=False, inplace = True)

### Total death cases

Death cases data is organised in a same way as confirmed cases (cummulative numbers over the time).

In [115]:
df_deaths = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')
df_deaths.fillna('None', inplace = True)

In [116]:
df_deaths.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20,3/21/20,3/22/20,3/23/20,3/24/20
0,None,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
1,None,Albania,41.1533,20.1683,0,0,0,0,0,0,...,1,1,1,2,2,2,2,2,4,5
2,None,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,4,4,4,7,9,11,15,17,17,19
3,None,Andorra,42.5063,1.5218,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
4,None,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [117]:
df_deaths['Last cumulative'] = df_deaths.iloc[:, -1]
print('Number of death cases by', date.today()- timedelta(days=1))

Number of death cases by 2020-03-24

In [118]:
total_deaths = df_deaths[['Country/Region', 'Last cumulative']]
total_deaths= total_deaths.groupby('Country/Region')['Last cumulative'].sum().to_frame()
total_deaths.sort_values('Last cumulative', ascending=False, inplace = True)

### Global mortality rate, %

In [119]:
all_cases = total_confirmed.join(total_deaths, lsuffix='_confirmed', rsuffix='_deaths')
all_cases.rename(columns={'Last cumulative_confirmed':'Total confirmed',
                         'Last cumulative_deaths':'Total deaths'}, inplace = True)
all_cases['mortality rate, %'] = round(all_cases['Total deaths']/all_cases['Total confirmed']*100,2)

In [120]:
all_cases

,Total confirmed,Total deaths,"mortality rate, %"
Country/Region,,,
China,81591,3281,4.02
Italy,69176,6820,9.86
US,53740,706,1.31
Spain,39885,2808,7.04
Germany,32986,157,0.48
Iran,24811,1934,7.79
France,22622,1102,4.87
Switzerland,9877,122,1.24
"Korea, South",9037,120,1.33
United Kingdom,8164,423,5.18
Netherlands,5580,277,4.96
Austria,5283,28,0.53
Belgium,4269,122,2.86
Norway,2863,12,0.42
Canada,2790,26,0.93
Portugal,2362,33,1.40
Sweden,2286,36,1.57
Brazil,2247,46,2.05
Australia,2044,8,0.39
Israel,1930,3,0.16
Turkey,1872,44,2.35
Denmark,1718,32,1.86
Malaysia,1624,16,0.99
Czechia,1394,3,0.22
Ireland,1329,7,0.53
Japan,1193,43,3.60
Luxembourg,1099,8,0.73
Ecuador,1082,27,2.50
Pakistan,972,7,0.72
Chile,922,2,0.22
...,...,...,...
Fiji,4,0,0.00
Djibouti,3,0,0.00
Niger,3,0,0.00
Chad,3,0,0.00
Central African Republic,3,0,0.00
Antigua and Barbuda,3,0,0.00
Angola,3,0,0.00
Zambia,3,0,0.00
Cabo Verde,3,1,33.33
Zimbabwe,3,1,33.33
Sudan,3,1,33.33
Mozambique,3,0,0.00
Gambia,3,1,33.33
Saint Lucia,3,0,0.00
Liberia,3,0,0.00
Laos,2,0,0.00
Nepal,2,0,0.00
Nicaragua,2,0,0.00
Mauritania,2,0,0.00
Dominica,2,0,0.00
Bhutan,2,0,0.00
Libya,1,0,0.00
Papua New Guinea,1,0,0.00
Syria,1,0,0.00
Belize,1,0,0.00
Saint Vincent and the Grenadines,1,0,0.00
Grenada,1,0,0.00
Timor-Leste,1,0,0.00
Eritrea,1,0,0.00
Somalia,1,0,0.00

In [137]:
# sort countries with respect of Total confirmed
top_30 = all_cases[:30]
# Create figure with secondary y-axis
fig = make_subplots(specs=[[{"secondary_y": True}]])

# Add traces
fig.add_trace(
    go.Scatter(x=top_30.index, y=top_30['Total confirmed'], name="Number of confirmed cases", 
               line = dict(color = '#F73309')),
    secondary_y=False,
)

fig.add_trace(
    go.Scatter(x=top_30.index, y=top_30['mortality rate, %'], name="Mortality rate",
               line = dict(color = '#B2AAA9')),
    secondary_y=True,
)

# Add figure title
fig.update_layout(
    title_text="Number of confirmed cases vs Mortality rate", template = 'none'
)

# Set y-axes titles
fig.update_yaxes(title_text="<b>Total confirmed</b>", secondary_y=False)
fig.update_yaxes(title_text="<b>mortality rate, %</b>", secondary_y=True)

fig.show()

### Measurements in dynamic

In [139]:
# confirmed cases
dates = df_confirmed.iloc[:, 4:-1].columns.to_list()
confirmed_melted = pd.melt(df_confirmed.iloc[:, :-1], id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], 
        value_vars=dates)
confirmed_melted.rename(columns = {'variable':'confirmed_date',
                                  'value':'confirmed cases'}, inplace = True)
confirmed_melted.head(10)

,Province/State,Country/Region,Lat,Long,confirmed_date,confirmed cases
0,None,Afghanistan,33.0000,65.0000,1/22/20,0
1,None,Albania,41.1533,20.1683,1/22/20,0
2,None,Algeria,28.0339,1.6596,1/22/20,0
3,None,Andorra,42.5063,1.5218,1/22/20,0
4,None,Angola,-11.2027,17.8739,1/22/20,0
5,None,Antigua and Barbuda,17.0608,-61.7964,1/22/20,0
6,None,Argentina,-38.4161,-63.6167,1/22/20,0
7,None,Armenia,40.0691,45.0382,1/22/20,0
8,Australian Capital Territory,Australia,-35.4735,149.0124,1/22/20,0
9,New South Wales,Australia,-33.8688,151.2093,1/22/20,0

In [141]:
# deaths cases
df_deaths

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20,3/21/20,3/22/20,3/23/20,3/24/20,Last cumulative
0,None,Afghanistan,33.000000,65.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1
1,None,Albania,41.153300,20.168300,0,0,0,0,0,0,...,1,1,2,2,2,2,2,4,5,5
2,None,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,4,4,7,9,11,15,17,17,19,19
3,None,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1
4,None,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,None,Antigua and Barbuda,17.060800,-61.796400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,None,Argentina,-38.416100,-63.616700,0,0,0,0,0,0,...,2,2,2,3,3,4,4,4,6,6
7,None,Armenia,40.069100,45.038200,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,0,0,...,2,4,5,5,6,6,6,6,7,7
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Queensland,Australia,-28.016700,153.400000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,Tasmania,Australia,-41.454500,145.970700,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
16,None,Austria,47.516200,14.550100,0,0,0,0,0,0,...,3,3,4,6,6,8,16,21,28,28
17,None,Azerbaijan,40.143100,47.576900,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
18,None,Bahamas,25.034300,-77.396300,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,None,Bahrain,26.027500,50.550000,0,0,0,0,0,0,...,1,1,1,1,1,1,2,2,3,3
20,None,Bangladesh,23.685000,90.356300,0,0,0,0,0,0,...,0,0,1,1,1,2,2,3,4,4
21,None,Barbados,13.193900,-59.543200,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,None,Belarus,53.709800,27.953400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,None,Belgium,50.833300,4.000000,0,0,0,0,0,0,...,5,10,14,21,37,67,75,88,122,122
24,None,Benin,9.307700,2.315800,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,None,Bhutan,27.514200,90.433600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,None,Bolivia,-16.290200,-63.588700,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,None,Bosnia and Herzegovina,43.915900,17.679100,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,3,3
28,None,Brazil,-14.235000,-51.925300,0,0,0,0,0,0,...,0,1,3,6,11,15,25,34,46,46
29,None,Brunei,4.535300,114.727700,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,None,Trinidad and Tobago,10.691800,-61.222500,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
212,None,Tunisia,34.000000,9.000000,0,0,0,0,0,0,...,0,0,0,1,1,1,3,3,4,4
213,None,Turkey,38.963700,35.243300,0,0,0,0,0,0,...,0,1,1,3,4,9,30,37,44,44
214,None,Uganda,1.000000,32.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
215,None,Ukraine,48.379400,31.165600,0,0,0,0,0,0,...,1,2,2,2,3,3,3,3,3,3
216,None,United Arab Emirates,24.000000,54.000000,0,0,0,0,0,0,...,0,0,0,0,2,2,2,2,2,2
217,Bermuda,United Kingdom,32.307800,-64.750500,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
218,Cayman Islands,United Kingdom,19.313300,-81.254600,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
219,Channel Islands,United Kingdom,49.372300,-2.364400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
220,Gibraltar,United Kingdom,36.140800,-5.353600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
221,Isle of Man,United Kingdom,54.236100,-4.548100,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
222,Montserrat,United Kingdom,16.742500,-62.187400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
223,None,United Kingdom,55.378100,-3.436000,0,0,0,0,0,0,...,55,55,71,137,177,233,281,335,422,422
224,None,Uruguay,-32.522800,-55.765800,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
225,None,US,37.090200,-95.712900,0,0,0,0,0,0,...,85,108,118,200,244,307,417,557,706,706
226,None,Uzbekistan,41.377500,64.585300,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
227,None,Venezuela,6.423800,-66.589700,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
228,None,Vietnam,16.000000,108.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
229,None,Zambia,-15.416700,28.283300,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
230,None,Zimbabwe,-20.000000,30.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
231,Diamond Princess,Canada,0.000000,0.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1
232,None,Dominica,15.415000,-61.371000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
233,None,Grenada,12.116500,-61.679000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
234,None,Mozambique,-18.665695,35.529562,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
235,None,Syria,34.802075,38.996815,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
236,None,Timor-Leste,-8.874217,125.727539,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
237,None,Belize,13.193900,-59.543200,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
238,Recovered,Canada,0.000000,0.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
239,None,Laos,19.856270,102.495496,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
240,None,Libya,26.335100,17.228331,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
pd.merge(confirmed_melted, df_deaths,  how='left', left_on=['A_c1','c2'], right_on = ['B_c1','c2'])